pipeline {
    agent any

    stages {
        stage('Testovi jedinice') {
            steps {
                sh 'docker build -f fibonacci/Dockerfile.test -t go_test fibonacci'
                sh 'docker run --rm go_test > tests.xml'
            }
        }
        stage('Izgradnja slike') {
            steps {
                script {
                    docker.withRegistry('https://docker.io', 'dockerhub') {
                        def i = docker.build("sokac/fibonacci:${BUILD_NUMBER}", '-f fibonacci/Dockerfile fibonacci/')
                        i.push()
                    }
                }
            }
        }
        stage('Testiranje slike') {
            steps {
                script {
                    docker.withRegistry('https://docker.io', 'dockerhub') {
                        def i = docker.image("sokac/fibonacci:${BUILD_NUMBER}")
                        i.withRun { c->
                            sleep 1 // cekaj sekundu
                            def ii = docker.build('sokac/fibonacci_integration', '-f fibonacci/Dockerfile.integration fibonacci/')
                            ii.inside("--shm-size=1g --link ${c.id}:app") {
                                sh 'cd fibonacci && CYPRESS_baseUrl=http://app:8888/ /node_modules/.bin/cypress run -r junit'
                            }
                        }
                    }
                }
            }
        }
        stage('Objava slike') {
            steps {
                script {
                    docker.withRegistry('https://docker.io', 'dockerhub') {
                        def i = docker.image("sokac/fibonacci:${BUILD_NUMBER}")
                        i.push('latest')
                    }
                }
            }
        }
    }

    post {
        always {
            junit 'tests.xml'
            junit 'fibonacci/test-results.xml'
        }
    }
}
